"""Rename latency to duration in playground_traces

Revision ID: 125b06883c8d
Revises: ed2ab69fa339
Create Date: 2026-01-14 15:53:05.878139
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '125b06883c8d'
down_revision = 'ed2ab69fa339'
branch_labels = None
depends_on = None


def upgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  with op.batch_alter_table('playground_traces', schema=None) as batch_op:
    batch_op.alter_column('latency_ms', new_column_name='duration_ms')

  # ### end Alembic commands ###


def downgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  with op.batch_alter_table('playground_traces', schema=None) as batch_op:
    batch_op.alter_column('duration_ms', new_column_name='latency_ms')

  # ### end Alembic commands ###
