"""rename_agent_config_to_context

Revision ID: 20067ef744e4
Revises: 827a40689071
Create Date: 2026-01-06 16:25:46.291327
"""

from alembic import op

# revision identifiers, used by Alembic.
revision = '20067ef744e4'
down_revision = '827a40689071'
branch_labels = None
depends_on = None


def upgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  with op.batch_alter_table('runs', schema=None) as batch_op:
    batch_op.alter_column(
        'agent_config_snapshot', new_column_name='agent_context_snapshot'
    )

  # ### end Alembic commands ###


def downgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  with op.batch_alter_table('runs', schema=None) as batch_op:
    batch_op.alter_column(
        'agent_context_snapshot', new_column_name='agent_config_snapshot'
    )

  # ### end Alembic commands ###
