"""Rename latency to duration and make derived

Revision ID: 3ca5b4628874
Revises: 20067ef744e4
Create Date: 2026-01-14 15:49:53.187137
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ca5b4628874'
down_revision = '20067ef744e4'
branch_labels = None
depends_on = None


def upgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  with op.batch_alter_table('trials', schema=None) as batch_op:
    batch_op.alter_column('latency_ms', new_column_name='service_duration_ms')

  # ### end Alembic commands ###


def downgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  with op.batch_alter_table('trials', schema=None) as batch_op:
    batch_op.alter_column('service_duration_ms', new_column_name='latency_ms')

  # ### end Alembic commands ###
