"""add concurrency to run

Revision ID: 53caba6952b0
Revises: a22be0585aee
Create Date: 2026-02-19 18:26:25.800608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53caba6952b0'
down_revision = 'a22be0585aee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust ###
    op.add_column('runs', sa.Column('concurrency', sa.Integer(), server_default='2', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust ###
    op.drop_column('runs', 'concurrency')
    # ### end Alembic commands ###
