"""remove datasource fields from test suite

Revision ID: 827a40689071
Revises: 8a3312245187
Create Date: 2026-01-06 00:45:37.391161
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '827a40689071'
down_revision = '8a3312245187'
branch_labels = None
depends_on = None


def upgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  with op.batch_alter_table('test_suite_snapshots', schema=None) as batch_op:
    batch_op.drop_column('datasource_type')
    batch_op.drop_column('datasource_config')
    batch_op.drop_column('datasource_name')

  with op.batch_alter_table('test_suites', schema=None) as batch_op:
    batch_op.drop_column('datasource_type')
    batch_op.drop_column('datasource_config')
    batch_op.drop_column('datasource_name')

  with op.batch_alter_table('trials', schema=None) as batch_op:
    batch_op.drop_column('score')

  # ### end Alembic commands ###


def downgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  with op.batch_alter_table('trials', schema=None) as batch_op:
    batch_op.add_column(sa.Column('score', sa.FLOAT(), nullable=True))

  with op.batch_alter_table('test_suites', schema=None) as batch_op:
    batch_op.add_column(
        sa.Column('datasource_name', sa.VARCHAR(), nullable=True)
    )
    batch_op.add_column(
        sa.Column('datasource_config', sqlite.JSON(), nullable=True)
    )
    batch_op.add_column(
        sa.Column('datasource_type', sa.VARCHAR(), nullable=True)
    )

  with op.batch_alter_table('test_suite_snapshots', schema=None) as batch_op:
    batch_op.add_column(
        sa.Column('datasource_name', sa.VARCHAR(), nullable=True)
    )
    batch_op.add_column(
        sa.Column('datasource_config', sqlite.JSON(), nullable=True)
    )
    batch_op.add_column(
        sa.Column('datasource_type', sa.VARCHAR(), nullable=True)
    )

  # ### end Alembic commands ###
