"""Sync with models.

Revision ID: 8a3312245187
Revises: e8fe334fbbf5
Create Date: 2026-01-05 15:51:04.363512
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a3312245187'
down_revision = 'e8fe334fbbf5'
branch_labels = None
depends_on = None


def upgrade() -> None:
  """Applies the migration."""
  # ### commands auto generated by Alembic - please adjust! ###
  with op.batch_alter_table('runs', schema=None) as batch_op:
    batch_op.alter_column(
        'status',
        existing_type=sa.VARCHAR(length=9),
        type_=sa.Enum(
            'PENDING',
            'RUNNING',
            'EXECUTING',
            'EVALUATING',
            'COMPLETED',
            'FAILED',
            'CANCELLED',
            name='runstatus',
        ),
        existing_nullable=False,
    )

  with op.batch_alter_table('trials', schema=None) as batch_op:
    batch_op.add_column(sa.Column('error_traceback', sa.Text(), nullable=True))
    batch_op.add_column(
        sa.Column('failed_stage', sa.String(length=50), nullable=True)
    )
    batch_op.alter_column(
        'status',
        existing_type=sa.VARCHAR(length=9),
        type_=sa.Enum(
            'PENDING',
            'RUNNING',
            'EXECUTING',
            'EVALUATING',
            'COMPLETED',
            'FAILED',
            'CANCELLED',
            name='runstatus',
        ),
        existing_nullable=False,
    )

  # ### end Alembic commands ###


def downgrade() -> None:
  """Reverts the migration."""
  # ### commands auto generated by Alembic - please adjust! ###
  with op.batch_alter_table('trials', schema=None) as batch_op:
    batch_op.alter_column(
        'status',
        existing_type=sa.Enum(
            'PENDING',
            'RUNNING',
            'EXECUTING',
            'EVALUATING',
            'COMPLETED',
            'FAILED',
            'CANCELLED',
            name='runstatus',
        ),
        type_=sa.VARCHAR(length=9),
        existing_nullable=False,
    )
    batch_op.drop_column('failed_stage')
    batch_op.drop_column('error_traceback')

  with op.batch_alter_table('runs', schema=None) as batch_op:
    batch_op.alter_column(
        'status',
        existing_type=sa.Enum(
            'PENDING',
            'RUNNING',
            'EXECUTING',
            'EVALUATING',
            'COMPLETED',
            'FAILED',
            'CANCELLED',
            name='runstatus',
        ),
        type_=sa.VARCHAR(length=9),
        existing_nullable=False,
    )

  # ### end Alembic commands ###
