"""Add Looker credentials to Agent

Revision ID: a26b5bc93f48
Revises: c67b9fdcae84
Create Date: 2025-12-31 23:42:58.434421
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a26b5bc93f48'
down_revision = 'c67b9fdcae84'
branch_labels = None
depends_on = None


def upgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.add_column(
      'agents', sa.Column('looker_client_id', sa.String(), nullable=True)
  )
  op.add_column(
      'agents', sa.Column('looker_client_secret', sa.String(), nullable=True)
  )
  # ### end Alembic commands ###


def downgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_column('agents', 'looker_client_secret')
  op.drop_column('agents', 'looker_client_id')
  # ### end Alembic commands ###
