"""add_datasource_config_to_suite

Revision ID: cb607eef9ff8
Revises: b61defd0d9b8
Create Date: 2025-12-30 23:50:00.536052
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb607eef9ff8'
down_revision = 'b61defd0d9b8'
branch_labels = None
depends_on = None


def upgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.add_column(
      'test_suite_snapshots',
      sa.Column('datasource_config', sa.JSON(), nullable=True),
  )
  op.add_column(
      'test_suites', sa.Column('datasource_config', sa.JSON(), nullable=True)
  )
  # ### end Alembic commands ###


def downgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_column('test_suites', 'datasource_config')
  op.drop_column('test_suite_snapshots', 'datasource_config')
  # ### end Alembic commands ###
