"""remove calculated columns from runs

Revision ID: e8fe334fbbf5
Revises: 7cdc4df909dc
Create Date: 2026-01-04 01:50:39.363548
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8fe334fbbf5'
down_revision = '7cdc4df909dc'
branch_labels = None
depends_on = None


def upgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_column('runs', 'passed_examples')
  op.drop_column('runs', 'total_examples')
  op.drop_column('runs', 'failed_examples')
  # ### end Alembic commands ###


def downgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.add_column(
      'runs', sa.Column('failed_examples', sa.INTEGER(), nullable=False)
  )
  op.add_column(
      'runs',
      sa.Column(
          'total_examples',
          sa.INTEGER(),
          server_default=sa.text('0'),
          nullable=False,
      ),
  )
  op.add_column(
      'runs',
      sa.Column(
          'passed_examples',
          sa.INTEGER(),
          server_default=sa.text('0'),
          nullable=False,
      ),
  )
  # ### end Alembic commands ###
