"""Remove service_duration_ms column

Revision ID: ed2ab69fa339
Revises: 3ca5b4628874
Create Date: 2026-01-14 15:51:35.224945
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed2ab69fa339'
down_revision = '3ca5b4628874'
branch_labels = None
depends_on = None


def upgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  with op.batch_alter_table('trials', schema=None) as batch_op:
    batch_op.drop_column('service_duration_ms')

  # ### end Alembic commands ###


def downgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  with op.batch_alter_table('trials', schema=None) as batch_op:
    batch_op.add_column(
        sa.Column('service_duration_ms', sa.INTEGER(), nullable=True)
    )

  # ### end Alembic commands ###
